name: string_width
description: Get the visual width of a string - the number of columns required to display it
version: 0.1.0
homepage: https://github.com/hyiso/string_width

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  characters: ^1.2.1
  emoji_regex: ^0.0.2

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
