name: string_width
description: Get the visual width of a string - the number of columns required to display it
version: 0.1.5
homepage: https://github.com/hyiso/string_width

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  ansi_strip: ^0.1.0
  characters: ^1.2.1
  east_asian_width: ^1.0.1
  emoji_regex: ^0.0.4

dev_dependencies:
  commitlint_cli: ^0.4.0-pre.0
  husky: ^0.1.6
  lint_staged: ">=0.2.0 <0.4.0"
  lints: ^2.0.0
  test: ^1.16.0

lint_staged:
  '**.dart': dart fix --apply && dart format --fix